#import "DocumentScanner.h"
#import <VisionKit/VisionKit.h>
#import "DocumentScanner-Swift.h"

@interface DocumentScanner ()
@property (nonatomic, strong) DocumentScannerImpl *impl;
@end

@implementation DocumentScanner
RCT_EXPORT_MODULE()

#if !RCT_NEW_ARCH_ENABLED
// Old architecture bridge ONLY when New Arch turned off
RCT_EXPORT_METHOD(scanDocument:(NSDictionary *)options
                  resolve:(RCTPromiseResolveBlock)resolve
                  reject:(RCTPromiseRejectBlock)reject)
{
  if (!self.impl) {
    self.impl = [DocumentScannerImpl new];
  }
  [self.impl scanDocument:options resolve:resolve reject:reject];
}
#endif

#if RCT_NEW_ARCH_ENABLED
// New architecture (TurboModule) entrypoint generated by codegen
- (void)scanDocument:(JS::NativeDocumentScanner::ScanDocumentOptions &)options
             resolve:(RCTPromiseResolveBlock)resolve
              reject:(RCTPromiseRejectBlock)reject
{
  if (!self.impl) {
    self.impl = [DocumentScannerImpl new];
  }
  NSMutableDictionary *dict = [NSMutableDictionary new];
  if (options.responseType() != nil) {
    dict[@"responseType"] = options.responseType();
  }
  if (options.croppedImageQuality().has_value()) {
    dict[@"croppedImageQuality"] = @(options.croppedImageQuality().value());
  }
  if (options.maxNumDocuments().has_value()) {
    dict[@"maxNumDocuments"] = @(options.maxNumDocuments().value());
  }
  [self.impl scanDocument:dict resolve:resolve reject:reject];
}

- (std::shared_ptr<facebook::react::TurboModule>)getTurboModule:
    (const facebook::react::ObjCTurboModule::InitParams &)params
{
  return std::make_shared<facebook::react::NativeDocumentScannerSpecJSI>(params);
}
#endif
@end